#!/usr/bin/env python3
"""
创建 Windows setup.exe 安装包
Create Windows setup.exe Installer
使用 Inno Setup 创建专业的 Windows 安装程序
"""

import os
import sys
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path
from datetime import datetime


class SetupExeBuilder:
    """setup.exe 安装包构建器"""
    
    def __init__(self):
        self.project_root = Path(__file__).parent.absolute()
        self.app_name = "E文件解析工具"
        self.display_name = "E文件解析工具 (优化版)"
        self.version = "2.1.3"
        self.manufacturer = "国家电投云南国际"
        
        # Inno Setup 路径
        self.innosetup_path = self.find_innosetup()
        
        # 要包含的文件
        self.files_to_include = [
            ("qt_app_v2_optimized_final.py", "源代码"),
            ("efile_parser_optimized.py", "源代码"),
            ("db_utils_optimized.py", "源代码"),
            ("requirements_optimized.txt", "源代码"),
            ("build_qt_app_v2_optimized.py", "源代码"),
            ("spic_icon.ico", "资源文件"),
            ("spic_logo.png", "资源文件"),
            ("README.md", "文档"),
            ("南方电网新能源数据上送规范 V3.3修订版（2022.2月）.pdf", "文档"),
        ]
        
        # 示例数据文件
        self.sample_data_files = []
        self.collect_sample_data()
    
    def find_innosetup(self):
        """查找 Inno Setup 安装路径"""
        possible_paths = [
            r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
            r"C:\Program Files\Inno Setup 6\ISCC.exe",
            r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe",
            r"C:\Program Files\Inno Setup 5\ISCC.exe",
        ]
        
        for path in possible_paths:
            iscc_exe = Path(path)
            if iscc_exe.exists():
                print(f"✅ 找到 Inno Setup: {path}")
                return iscc_exe
        
        print("❌ 未找到 Inno Setup，请先安装 Inno Setup")
        print("下载地址: https://jrsoftware.org/isdl.php")
        return None
    
    def collect_sample_data(self):
        """收集示例数据文件"""
        sample_data_dir = self.project_root / "102E2601"
        if sample_data_dir.exists():
            dat_files = list(sample_data_dir.glob("*.dat"))
            if dat_files:
                # 取最新的3个文件
                dat_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
                self.sample_data_files = dat_files[:3]
                print(f"📁 找到 {len(self.sample_data_files)} 个示例数据文件")
    
    def create_iss_file(self, temp_dir):
        """创建 Inno Setup 脚本文件 (.iss)"""
        iss_content = f'''; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "{self.display_name}"
#define MyAppVersion "{self.version}"
#define MyAppPublisher "{self.manufacturer}"
#define MyAppURL "https://www.spic.com.cn/"
#define MyAppExeName "qt_app_v2_optimized_final.py"
#define MyAppSetupExeName "setup.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E9B8F3C2-4D5A-4F1B-8C2E-9F7A6B5D3C1E}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
;AppVerName={{#MyAppName}} {{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DisableDirPage=no
DisableProgramGroupPage=yes
OutputBaseFilename={{#MyAppSetupExeName}}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=administrator
CreateAppDir=yes

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "创建桌面快捷方式"; GroupDescription: "附加图标"; Flags: unchecked
Name: "associate_dat"; Description: "关联 .dat 文件"; GroupDescription: "文件关联"; Flags: unchecked

[Files]
; 源代码文件
Source: "源代码\\qt_app_v2_optimized_final.py"; DestDir: "{{app}}\\源代码"; Flags: ignoreversion
Source: "源代码\\efile_parser_optimized.py"; DestDir: "{{app}}\\源代码"; Flags: ignoreversion
Source: "源代码\\db_utils_optimized.py"; DestDir: "{{app}}\\源代码"; Flags: ignoreversion
Source: "源代码\\requirements_optimized.txt"; DestDir: "{{app}}\\源代码"; Flags: ignoreversion
Source: "源代码\\build_qt_app_v2_optimized.py"; DestDir: "{{app}}\\源代码"; Flags: ignoreversion

; 资源文件
Source: "资源文件\\spic_icon.ico"; DestDir: "{{app}}\\资源文件"; Flags: ignoreversion
Source: "资源文件\\spic_logo.png"; DestDir: "{{app}}\\资源文件"; Flags: ignoreversion

; 文档文件
Source: "文档\\README.md"; DestDir: "{{app}}\\文档"; Flags: ignoreversion
Source: "文档\\南方电网新能源数据上送规范 V3.3修订版（2022.2月）.pdf"; DestDir: "{{app}}\\文档"; Flags: ignoreversion

; 快速启动脚本
Source: "快速启动.bat"; DestDir: "{{app}}"; Flags: ignoreversion

; 安装指南
Source: "安装指南.md"; DestDir: "{{app}}"; Flags: ignoreversion

; 示例数据文件
'''
        
        # 添加示例数据文件
        for sample_file in self.sample_data_files:
            file_name = sample_file.name
            iss_content += f'Source: "示例数据\\{file_name}"; DestDir: "{{app}}\\示例数据"; Flags: ignoreversion\n'
        
        iss_content += '''
[Icons]
Name: "{{autoprograms}}\\{{#MyAppName}}"; Filename: "{{app}}\\源代码\\{{#MyAppExeName}}"; WorkingDir: "{{app}}\\源代码"; IconFilename: "{{app}}\\资源文件\\spic_icon.ico"
Name: "{{autoprograms}}\\快速启动"; Filename: "{{app}}\\快速启动.bat"; WorkingDir: "{{app}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\源代码\\{{#MyAppExeName}}"; WorkingDir: "{{app}}\\源代码"; IconFilename: "{{app}}\\资源文件\\spic_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\快速启动.bat"; Description: "{{cm:LaunchProgram,{{#MyAppName}}}}"; Flags: nowait postinstall skipifsilent

[Registry]
; 创建文件关联
Root: HKCR; Subkey: ".dat"; ValueType: string; ValueName: ""; ValueData: "EFileParser.dat"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "EFileParser.dat"; ValueType: string; ValueName: ""; ValueData: "E文件解析工具数据文件"; Flags: uninsdeletekey
Root: HKCR; Subkey: "EFileParser.dat\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: """{{app}}\\源代码\\{{#MyAppExeName}}"" ""%1"""; Flags: uninsdeletevalue
Root: HKCR; Subkey: "EFileParser.dat\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{{app}}\\资源文件\\spic_icon.ico"; Flags: uninsdeletevalue

[Code]
function InitializeSetup(): Boolean;
begin
  Result := True;
  
  if not RegKeyExists(HKLM, 'SOFTWARE\\Python\\PythonCore') then
  begin
    MsgBox('此应用程序需要 Python 3.8 或更高版本。' + #13#10 +
           '请先安装 Python，然后重新运行安装程序。', mbError, MB_OK);
    Result := False;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    MsgBox('安装完成！' + #13#10#13#10 +
           '请按照以下步骤使用应用程序：' + #13#10 +
           '1. 双击桌面上的快捷方式或开始菜单中的程序' + #13#10 +
           '2. 首次运行前请安装 Python 依赖：' + #13#10 +
           '   pip install -r requirements_optimized.txt' + #13#10 +
           '3. 然后运行 qt_app_v2_optimized_final.py' + #13#10#13#10 +
           '安装位置: {{app}}', mbInformation, MB_OK);
  end;
end;
'''
        
        iss_file = temp_dir / "setup.iss"
        with open(iss_file, 'w', encoding='utf-8') as f:
            f.write(iss_content)
        
        print(f"✅ 创建 Inno Setup 脚本: {iss_file}")
        return iss_file
    
    def create_installation_guide(self, temp_dir):
        """创建安装指南"""
        guide_content = f"""# E文件解析工具 安装指南

## 版本信息
- 版本: {self.version}
- 发布时间: {datetime.now().strftime('%Y-%m-%d')}
- 制造商: {self.manufacturer}

## 安装步骤

### 1. 运行安装程序
双击 setup.exe 文件开始安装。

### 2. 选择安装位置
安装程序会提示您选择安装目录，默认安装到 Program Files 文件夹。

### 3. 选择安装选项
- ✅ 创建开始菜单快捷方式
- ☐ 创建桌面快捷方式（可选）
- ☐ 关联 .dat 文件（可选）

### 4. 完成安装
安装完成后，您可以在以下位置找到应用程序：
- 开始菜单: {self.app_name}
- 桌面: E文件解析工具 快捷方式（如果选择了该选项）
- 安装目录: 源代码\\qt_app_v2_optimized_final.py

## 使用方法

### 1. 安装 Python 依赖
首次使用前，请安装必要的 Python 依赖：
```bash
cd "安装目录\\源代码"
pip install -r requirements_optimized.txt
```

### 2. 运行应用程序
```bash
cd "安装目录\\源代码"
python qt_app_v2_optimized_final.py
```

### 3. 快速启动
双击桌面上的快捷方式或使用开始菜单中的"快速启动"选项。

### 4. 文件关联
如果安装时选择了文件关联选项，双击 .dat 文件可以直接用本程序打开。

## 卸载方法

### 方法一：通过控制面板
1. 打开控制面板
2. 选择"程序和功能"
3. 找到"{self.display_name}"
4. 点击"卸载"

### 方法二：通过开始菜单
在开始菜单的程序列表中找到"{self.app_name}"，选择卸载选项。

## 包含文件

### 源代码
- qt_app_v2_optimized_final.py - 主应用程序
- efile_parser_optimized.py - E文件解析器
- db_utils_optimized.py - 数据库工具
- requirements_optimized.txt - 依赖列表
- build_qt_app_v2_optimized.py - 构建脚本

### 资源文件
- spic_icon.ico - 应用图标
- spic_logo.png - SPIC Logo

### 文档
- README.md - 项目说明
- 南方电网新能源数据上送规范 V3.3修订版（2022.2月）.pdf - 规范文档

### 示例数据
包含用于测试的示例 E文件

## 系统要求

- Windows 7 SP1 或更高版本
- Python 3.8 或更高版本
- PySide6 库（运行时需要）

## 技术支持

如有问题，请联系：
- 开发者: 陈丰
- 电话: 0871-65666603
- 单位: 国家电投云南国际 昆明生产运营中心

## 版权信息
© {datetime.now().year} {self.manufacturer} 版权所有
"""
        
        guide_file = temp_dir / "安装指南.md"
        with open(guide_file, 'w', encoding='utf-8') as f:
            f.write(guide_content)
        print(f"✅ 创建安装指南: {guide_file}")
        return guide_file
    
    def create_quick_start_script(self, temp_dir):
        """创建快速启动脚本"""
        script_content = '''@echo off
echo.
echo ================================
echo   E文件解析工具 快速启动
echo ================================
echo.
echo 1. 运行源代码版本
echo 2. 构建可执行文件
echo 3. 查看安装指南
echo 4. 退出
echo.
set /p choice=请选择操作 (1-4): 

if "%choice%"=="1" goto run_source
if "%choice%"=="2" goto build_exe
if "%choice%"=="3" goto view_guide
if "%choice%"=="4" goto exit_script

:run_source
echo.
echo 正在启动源代码版本...
cd "源代码"
python qt_app_v2_optimized_final.py
goto end

:build_exe
echo.
echo 正在构建可执行文件...
cd "源代码"
python build_qt_app_v2_optimized.py
echo.
echo 构建完成！可执行文件在 dist 目录中。
pause
goto end

:view_guide
echo.
echo 正在打开安装指南...
start "" "安装指南.md"
goto end

:exit_script
echo.
echo 感谢使用！
goto end

:end
echo.
pause
'''
        
        script_file = temp_dir / "快速启动.bat"
        with open(script_file, 'w', encoding='utf-8') as f:
            f.write(script_content)
        print(f"✅ 创建快速启动脚本: {script_file}")
        return script_file
    
    def copy_files_to_temp(self, temp_dir):
        """复制文件到临时目录"""
        print("📁 复制文件到临时目录...")
        
        # 创建目录结构
        source_dir = temp_dir / "源代码"
        resource_dir = temp_dir / "资源文件"
        doc_dir = temp_dir / "文档"
        sample_dir = temp_dir / "示例数据"
        
        source_dir.mkdir(exist_ok=True)
        resource_dir.mkdir(exist_ok=True)
        doc_dir.mkdir(exist_ok=True)
        sample_dir.mkdir(exist_ok=True)
        
        # 复制文件
        for file_name, category in self.files_to_include:
            src_file = self.project_root / file_name
            if src_file.exists():
                if category == "源代码":
                    dst_file = source_dir / file_name
                elif category == "资源文件":
                    dst_file = resource_dir / file_name
                elif category == "文档":
                    dst_file = doc_dir / file_name
                
                shutil.copy2(src_file, dst_file)
                print(f"  ✅ 复制: {file_name}")
        
        # 复制示例数据
        for sample_file in self.sample_data_files:
            dst_file = sample_dir / sample_file.name
            shutil.copy2(sample_file, dst_file)
            print(f"  ✅ 复制示例数据: {sample_file.name}")
        
        # 创建安装指南和快速启动脚本
        self.create_installation_guide(temp_dir)
        self.create_quick_start_script(temp_dir)
    
    def build_setup_exe(self, temp_dir):
        """构建 setup.exe 安装程序"""
        if not self.innosetup_path:
            print("❌ 无法构建安装程序：未找到 Inno Setup")
            return False
        
        print("🔨 开始构建 setup.exe 安装程序...")
        
        # 创建 ISS 脚本文件
        iss_file = self.create_iss_file(temp_dir)
        
        # 运行 Inno Setup 编译器
        setup_exe_file = self.project_root / "setup.exe"
        
        iscc_cmd = [
            str(self.innosetup_path),
            "/Qp",  # 静默编译
            "/O" + str(self.project_root),
            str(iss_file)
        ]
        
        print(f"🔨 编译 Inno Setup 脚本...")
        try:
            result = subprocess.run(iscc_cmd, cwd=temp_dir, check=True,
                                  capture_output=True, text=True)
            print("  ✅ 编译成功")
            
            # 检查输出文件
            expected_output = self.project_root / "setup.exe"
            if expected_output.exists():
                print(f"  ✅ setup.exe 生成成功: {setup_exe_file.name}")
                return setup_exe_file
            else:
                print("  ❌ 未找到输出的 setup.exe 文件")
                return False
                
        except subprocess.CalledProcessError as e:
            print(f"  ❌ 编译失败: {e}")
            print(f"  错误输出: {e.stderr}")
            return False
    
    def build_installer(self):
        """构建安装程序"""
        print("=" * 60)
        print("🚀 开始构建 Windows setup.exe 安装包")
        print("=" * 60)
        print(f"📦 应用名称: {self.display_name}")
        print(f"📦 版本: {self.version}")
        print(f"📦 制造商: {self.manufacturer}")
        print(f"⏰ 时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("-" * 60)
        
        # 检查 Inno Setup
        if not self.innosetup_path:
            print("❌ 构建失败：未找到 Inno Setup")
            print("请先安装 Inno Setup: https://jrsoftware.org/isdl.php")
            return False
        
        # 创建临时目录
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            
            try:
                # 复制文件
                self.copy_files_to_temp(temp_path)
                
                # 构建 setup.exe
                setup_exe_file = self.build_setup_exe(temp_path)
                
                if setup_exe_file and setup_exe_file.exists():
                    # 显示构建信息
                    self.show_build_summary(setup_exe_file)
                    print("✅ setup.exe 安装程序构建成功！")
                    return True
                else:
                    print("❌ setup.exe 文件生成失败")
                    return False
                
            except Exception as e:
                print(f"❌ 构建过程中发生错误: {e}")
                return False
    
    def show_build_summary(self, setup_exe_file):
        """显示构建摘要"""
        print("\n" + "=" * 60)
        print("📊 构建摘要 (setup.exe)")
        print("=" * 60)
        
        # 文件大小
        file_size = setup_exe_file.stat().st_size / (1024 * 1024)
        print(f"📦 安装程序: {setup_exe_file.name}")
        print(f"📏 文件大小: {file_size:.2f} MB")
        print(f"📁 完整路径: {setup_exe_file}")
        
        print(f"⏰ 构建时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("=" * 60)
        print("\n🎉 setup.exe 安装程序已准备就绪！")
        print(f"您可以双击 {setup_exe_file.name} 文件来安装应用程序。")
        print("\n💡 setup.exe 安装程序特点:")
        print("- 专业的 Windows 安装界面")
        print("- 支持自定义安装选项")
        print("- 完整的卸载支持")
        print("- 文件关联功能")
        print("- 快捷方式创建")


def main():
    """主函数"""
    print("🔧 Windows setup.exe 安装包构建工具")
    print("使用 Inno Setup 创建专业的 Windows 安装程序")
    print("-" * 60)
    
    # 检查 Python 版本
    if sys.version_info < (3, 6):
        print("❌ 错误: 需要 Python 3.6 或更高版本")
        return 1
    
    # 创建构建器并构建安装程序
    builder = SetupExeBuilder()
    success = builder.build_installer()
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())